# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZ0ZLfsxPs9qfEb87pFuMGerXgD3AD01
"""

import pandas as pd
df=pd.read_csv('/content/Advertising.csv', index_col=0)

x=df.drop('Sales',axis=1)
y=df['Sales']

df.shape

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape

from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

lr.intercept_

lr.coef_

import pandas as pd

# Assuming x1, x2, x3 correspond to TV, Radio, Newspaper respectively
new_data = pd.DataFrame({
    'TV': [5],
    'Radio': [4],
    'Newspaper': [2]
})

y_pred = lr.predict(new_data)
print(f"The predicted value of y is: {y_pred[0]:.2f}")

lr.score(x_test,y_test)

lr.score(x_train,y_train)

from sklearn.model_selection import cross_val_score

cross_val_score(lr,x,y,cv=5).mean()

import joblib

# Save the model
joblib.dump(lr, 'linear_regression_model.sav')
print("Linear regression model saved as 'linear_regression_model.sav'")

import joblib
import pandas as pd

# Load the saved model
loaded_model = joblib.load('linear_regression_model.sav')
print("Linear regression model loaded successfully.")

# Define new data for prediction (you can change these values)
# Assuming TV, Radio, Newspaper are the features
prediction_data = pd.DataFrame({
    'TV': [5],
    'Radio': [4],
    'Newspaper': [2]
})

# Make a prediction
predicted_sales = loaded_model.predict(prediction_data)

print(f"Predicted Sales for TV=100, Radio=20, Newspaper=10: {predicted_sales[0]:.2f}")